apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: obligatorio
spec:
  type: ClusterIP
  selector:
    app: notification
  ports:
    - port: 8081
      targetPort: 8081
